#!/bin/bash

CHAT_ID=$(uci get telegram.settings.chat_id)
BOT_TOKEN=$(uci get telegram.settings.telegram_token)
MSGTR=$(uci get telegram.settings.message_thread_id)

# Detect if use ask for help
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` \"text message\""
  exit 0
fi

if [ -z "$1" ]
  then
    echo "Add message text as second arguments"
    exit 0
fi

if [ "$#" -ne 1 ]; then
    echo "You can pass only one argument. For string with spaces put it on quotes"
    exit 0
fi

# Send the message 
if [ -z "$MSGTR" ] || [ "$MSGTR" -eq 0 ]; then
  curl -s --data "text=$1" --data "chat_id=$CHAT_ID" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' > /dev/null
else
  curl -s --data "text=$1" --data "chat_id=$CHAT_ID" --data "message_thread_id=$MSGTR" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' > /dev/null
fi
